[package]
name = "cltool"
version = "0.1.0"
authors = ["chris <chris.j.gallo3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
